mysite/index/urls.py
#Imports
from django.urls import path
from . import views

app_name = 'index'
urlpatterns = [
    path('', views.index, name='index'),
]

mysite/mysite/urls.py
#Imports
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [ 
    
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('index/', include('index.urls')),
    path('', RedirectView.as_view(url='/index/', permanent=True)),
]

mysite/polls/urls.py
from django.urls import path
from . import views


app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/index/models.py
#Imports
from django.db import models
from django.utils import timezone

# Create your models here.

mysite/polls/models.py
# Create your models here.
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
        was_published_recently.admin_order_field = 'pub_date'
        was_published_recently.boolean = True
        was_published_recently.short_description = 'Published recently?'    

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

mysite/index/views.py
#Imports
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
# Create your views here.
def index(request):
    return render(request, 'index/index.html')


#def home(request):
#

mysite/polls/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from .models import Question
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from .models import Choice, Question
from django.utils import timezone


from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id) 
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

mysite/index/templates/index/index.html
<!doctype html>
<html lang="en">

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'index/styles2.css' %}">

<body>
<div class="main-nav">
        <ul class="nav">
          <li class="name">Django WebApp</li>
          <li><a href="{% url 'index:index' %}">Home</a></li>
          <li><a href="{% url 'polls:index' %}">Polls</a></li>
        </ul>
</div>

<main class="flex">
      <div class="card">
 <h2>Welcome!</h2>
          <p>This is my Django WebApp home page!</p>
          <div class="tab">
  <button class="tablinks active" onclick="openTab(event, 'Site')" id="defaultOpen">About This Site</button>
 <button class="tablinks" onclick="openTab(event, 'Me')">About Me</button>
  <button class="tablinks" onclick="openTab(event, 'Contact')">Contact Me</button>

</div>
 {% comment %} <div id="Experience" class="tabcontent cardTab" style="display: block;">
        <h2>Experience</h2>
        <p>Some of my past knowledge and skills include:</p>
        <ul class="skills">
          <li>Basic HTML</li>
          <li>Basic Java</li>
          <li>Basic Bash</li>
          <li>Bash Shell</li>
        </ul>
      </div> 
       
<div id="Hobbies" class="tabcontent cardTab" style="display: none;">
         <h2>Hobbies</h2>
    <p>Some activities I like to do when I have free time:</p>
    <ul class="skills">
    <li>Read</li>
        <li><a href="myphotos.html">Draw/Edit photos</a></li>
        <li><a href="mygames.html">Play Video Games</a></li>
    <li>Mess around with Computers</li>
    </ul>
</div>

<div id="Misc." class="tabcontent cardTab" style="display: none;">
  <h2>Miscellaneous</h2>
</div> {% endcomment %}
</div>

     

    </main>
    <script>
    function openTab(evt, categoryName) {
    // Declare all variables
    var i, tabcontent, tablinks;

    // Get all elements with class="tabcontent" and hide them
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }

    // Get all elements with class="tablinks" and remove the class "active"
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
    }

    // Show the current tab, and add an "active" class to the link that opened the tab
    document.getElementById(categoryName).style.display = "block";
    evt.currentTarget.className += " active";
} 
// Get the element with id="defaultOpen" and click on it
document.getElementById("defaultOpen").click();
    </script>
</body>
</html>

mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

mysite/polls/templates/polls/index.html
<!doctype html>
<html>
<head>

</head>

<body>

<header>

</header>
<div>

</div>
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

</body>


<html>

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
<a href="{% url 'polls:index' %}">Back to polls listing?</a>
<a href="{% url 'index:index' %}">Back to Site Home?</a>